### ISSUE TITLE
Failed build: Unable to determine Swift version for the following pods:

### ISSUE THREAD

**Issue by roberson34** [BananoCoin/kalium_wallet_flutter#9]
I am getting the following error when I run the app:

```
    Resolving dependencies of `Podfile`

    Comparing resolved specification to the sandbox manifest
      A FMDB
      A Firebase
      A FirebaseAnalytics
      A FirebaseAnalyticsInterop
      A FirebaseCore
      A FirebaseInstanceID
      A FirebaseMessaging
      A Flutter
      A GoogleAppMeasurement
      A GoogleUtilities
      A MTBBarcodeScanner
      A Protobuf
      A barcode_scan
      A device_info
      A file_picker
      A firebase_messaging
      A flutter_secure_storage
      A flutter_webview_plugin
      A local_auth
      A nanopb
      A package_info
      A path_provider
      A share
      A shared_preferences
      A sqflite
      A uni_links
      A vibrate

    Downloading dependencies

    -> Installing FMDB (2.7.5)
      > Copying FMDB from `/Users/farah/Library/Caches/CocoaPods/Pods/Release/FMDB/2.7.5-2ce00` to `Pods/FMDB`

    -> Installing Firebase (6.1.0)
      > Copying Firebase from `/Users/farah/Library/Caches/CocoaPods/Pods/Release/Firebase/6.1.0-8d77b` to `Pods/Firebase`

    -> Installing FirebaseAnalytics (6.0.1)
      > Copying FirebaseAnalytics from `/Users/farah/Library/Caches/CocoaPods/Pods/Release/FirebaseAnalytics/6.0.1-62930` to
      `Pods/FirebaseAnalytics`

    -> Installing FirebaseAnalyticsInterop (1.2.0)
      > Copying FirebaseAnalyticsInterop from `/Users/farah/Library/Caches/CocoaPods/Pods/Release/FirebaseAnalyticsInterop/1.2.0-efbe4` to
      `Pods/FirebaseAnalyticsInterop`

    -> Installing FirebaseCore (6.0.1)
      > Copying FirebaseCore from `/Users/farah/Library/Caches/CocoaPods/Pods/Release/FirebaseCore/6.0.1-66bde` to `Pods/FirebaseCore`

    -> Installing FirebaseInstanceID (4.1.0)
      > Copying FirebaseInstanceID from `/Users/farah/Library/Caches/CocoaPods/Pods/Release/FirebaseInstanceID/4.1.0-27bed` to
      `Pods/FirebaseInstanceID`

    -> Installing FirebaseMessaging (4.0.1)
      > Copying FirebaseMessaging from `/Users/farah/Library/Caches/CocoaPods/Pods/Release/FirebaseMessaging/4.0.1-31377` to
      `Pods/FirebaseMessaging`

    -> Installing Flutter (1.0.0)

    -> Installing GoogleAppMeasurement (6.0.1)
      > Copying GoogleAppMeasurement from `/Users/farah/Library/Caches/CocoaPods/Pods/Release/GoogleAppMeasurement/6.0.1-51d8d` to
      `Pods/GoogleAppMeasurement`

    -> Installing GoogleUtilities (6.2.0)
      > Copying GoogleUtilities from `/Users/farah/Library/Caches/CocoaPods/Pods/Release/GoogleUtilities/6.2.0-996e0` to
      `Pods/GoogleUtilities`

    -> Installing MTBBarcodeScanner (5.0.11)
      > Copying MTBBarcodeScanner from `/Users/farah/Library/Caches/CocoaPods/Pods/Release/MTBBarcodeScanner/5.0.11-f453b` to
      `Pods/MTBBarcodeScanner`

    -> Installing Protobuf (3.8.0)
      > Copying Protobuf from `/Users/farah/Library/Caches/CocoaPods/Pods/Release/Protobuf/3.8.0-3f617` to `Pods/Protobuf`

    -> Installing barcode_scan (0.0.1)

    -> Installing device_info (0.0.1)

    -> Installing file_picker (0.0.1)

    -> Installing firebase_messaging (0.0.1)

    -> Installing flutter_secure_storage (3.2.0)

    -> Installing flutter_webview_plugin (0.0.1)

    -> Installing local_auth (0.0.1)

    -> Installing nanopb (0.3.901)
      > Copying nanopb from `/Users/farah/Library/Caches/CocoaPods/Pods/Release/nanopb/0.3.901-2901f` to `Pods/nanopb`

    -> Installing package_info (0.0.1)

    -> Installing path_provider (0.0.1)

    -> Installing share (0.5.2)

    -> Installing shared_preferences (0.0.1)

    -> Installing sqflite (0.0.1)

    -> Installing uni_links (0.0.1)

    -> Installing vibrate (0.0.1)
      - Running pre install hooks
        - Podfile
    [!] Unable to determine Swift version for the following pods:

    - `vibrate` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set.
    Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0/lib/cocoapods/installer/xcode/target_validator.rb:122:in `verify_swift_pods_swift_version'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0/lib/cocoapods/installer.rb:578:in `validate_targets'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0/lib/cocoapods/installer.rb:158:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0/lib/cocoapods/command/install.rb:51:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `ios` with version `10.3` on target `Runner` because no platform was specified. Please specify a
    platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
```

**Comment by roberson34** [comment]
resolved. it was on my end.
